const infobox = document.querySelector(".infobox");

const combinacoes = [
  "block-end",
  "block-end center",
  "block-end inline-end",
  "block-end inline-start",
  "block-end span-inline-end",
  "block-end span-inline-start",
  "block-start",
  "block-start center",
  "block-start inline-end",
  "block-start inline-start",
  "block-start span-inline-end",
  "block-start span-inline-start",
  "bottom",
  "center bottom",
  "left bottom",
  "right bottom",
  "span-left bottom",
  "span-right bottom",
  "span-x-end bottom",
  "span-x-start bottom",
  "x-end bottom",
  "x-start bottom",
  "center",
  "center end",
  "center inline-end",
  "center inline-start",
  "left center",
  "right center",
  "self-block-end center",
  "self-block-start center",
  "center self-end",
  "center self-inline-end",
  "center self-inline-start",
  "center self-start",
  "center span-all",
  "span-block-end center",
  "span-block-start center",
  "center span-bottom",
  "center span-end",
  "center span-inline-end",
  "center span-inline-start",
  "span-left center",
  "span-right center",
  "span-self-block-end center",
  "span-self-block-start center",
  "center span-self-end",
  "center span-self-inline-end",
  "center span-self-inline-start",
  "center span-self-start",
  "center span-start",
  "center span-top",
  "span-x-end center",
  "span-x-start center",
  "center span-y-end",
  "center span-y-start",
  "center start",
  "center top",
  "x-end center",
  "x-start center",
  "center y-end",
  "center y-start",
  "end",
  "end center",
  "end span-all",
  "end span-end",
  "end span-start",
  "end start",
  "inline-end",
  "span-block-end inline-end",
  "span-block-start inline-end",
  "inline-start",
  "span-block-end inline-start",
  "span-block-start inline-start",
  "left",
  "left span-bottom",
  "left span-top",
  "left span-y-end",
  "left span-y-start",
  "left top",
  "left y-end",
  "left y-start",
  "right",
  "right span-bottom",
  "right span-top",
  "right span-y-end",
  "right span-y-start",
  "right top",
  "right y-end",
  "right y-start",
  "self-block-end",
  "self-block-end self-inline-end",
  "self-block-end self-inline-start",
  "self-block-end span-self-inline-end",
  "self-block-end span-self-inline-start",
  "self-block-start",
  "self-block-start self-inline-end",
  "self-block-start self-inline-start",
  "self-block-start span-self-inline-end",
  "self-block-start span-self-inline-start",
  "self-end",
  "self-end center",
  "self-end self-start",
  "self-end span-all",
  "self-end span-self-end",
  "self-end span-self-start",
  "self-inline-end",
  "span-self-block-end self-inline-end",
  "span-self-block-start self-inline-end",
  "self-inline-start",
  "span-self-block-end self-inline-start",
  "span-self-block-start self-inline-start",
  "self-start",
  "self-start center",
  "self-start self-end",
  "self-start span-all",
  "self-start span-self-end",
  "self-start span-self-start",
  "span-all",
  "span-all center",
  "span-all end",
  "span-all self-end",
  "span-all self-start",
  "span-block-end",
  "span-block-start",
  "span-bottom",
  "span-all span-end",
  "span-inline-end",
  "span-inline-start",
  "span-left",
  "span-right",
  "span-self-block-end",
  "span-self-block-start",
  "span-all span-self-end",
  "span-self-inline-end",
  "span-self-inline-start",
  "span-all span-self-start",
  "span-all span-start",
  "span-top",
  "span-x-end",
  "span-x-start",
  "span-y-end",
  "span-y-start",
  "span-all start",
  "top",
  "x-end",
  "x-start",
  "y-end",
  "y-start",
  "span-block-end span-inline-end",
  "span-block-end span-inline-start",
  "span-block-start span-inline-end",
  "span-block-start span-inline-start",
  "span-left span-bottom",
  "span-right span-bottom",
  "span-x-end span-bottom",
  "span-x-start span-bottom",
  "x-end span-bottom",
  "x-start span-bottom",
  "span-end",
  "span-end center",
  "span-end end",
  "span-end span-all",
  "span-end span-start",
  "span-end start",
  "span-left span-top",
  "span-left span-y-end",
  "span-left span-y-start",
  "span-left top",
  "span-left y-end",
  "span-left y-start",
  "span-right span-top",
  "span-right span-y-end",
  "span-right span-y-start",
  "span-right top",
  "span-right y-end",
  "span-right y-start",
  "span-self-block-end span-self-inline-end",
  "span-self-block-end span-self-inline-start",
  "span-self-block-start span-self-inline-end",
  "span-self-block-start span-self-inline-start",
  "span-self-end",
  "span-self-end center",
  "span-self-end self-end",
  "span-self-end self-start",
  "span-self-end span-all",
  "span-self-end span-self-start",
  "span-self-start",
  "span-self-start center",
  "span-self-start self-end",
  "span-self-start self-start",
  "span-self-start span-all",
  "span-self-start span-self-end",
  "span-start",
  "span-start center",
  "span-start end",
  "span-start span-all",
  "span-start span-end",
  "span-start start",
  "span-x-end span-top",
  "span-x-start span-top",
  "x-end span-top",
  "x-start span-top",
  "span-x-end span-y-end",
  "span-x-end span-y-start",
  "span-x-end top",
  "span-x-end y-end",
  "span-x-end y-start",
  "span-x-start span-y-end",
  "span-x-start span-y-start",
  "span-x-start top",
  "span-x-start y-end",
  "span-x-start y-start",
  "x-end span-y-end",
  "x-start span-y-end",
  "x-end span-y-start",
  "x-start span-y-start",
  "start",
  "start center",
  "start end",
  "start span-all",
  "start span-end",
  "start span-start",
  "x-end top",
  "x-start top",
  "x-end y-end",
  "x-end y-start",
  "x-start y-end",
  "x-start y-start"
];

combinacoes.sort();

const positionAreaForm = document.querySelector("#position-area-form");
const selectElem0 = document.querySelector("select");
const out = document.querySelector(".pre-output");

positionAreaForm.addEventListener("submit", (e) => { e.preventDefault(); });

selectElem0.addEventListener("change", definePositionArea);

function definePositionArea() {
  infobox.style.positionArea = selectElem0.value;
  out.innerHTML = infobox.style.positionArea;
}

for (const nome of combinacoes) {
  selectElem0.append(
    new Option(nome, nome)
  )
}